12/18/2024 10:30:02 - INFO - __main__ - ***** Running training *****
12/18/2024 10:30:02 - INFO - __main__ -   Num examples = 1566
12/18/2024 10:30:02 - INFO - __main__ -   Num Epochs = 100
12/18/2024 10:30:02 - INFO - __main__ -   Instantaneous batch size per device = 8
12/18/2024 10:30:02 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 8
12/18/2024 10:30:02 - INFO - __main__ -   Gradient Accumulation steps = 1
12/18/2024 10:30:02 - INFO - __main__ -   Total optimization steps = 19600
  1%|â–‰                                                                                              | 195/19600 [00:09<15:20, 21.08it/s]Traceback (most recent call last):
  File "/home/agrosavia/cacao-hf/main.py", line 827, in <module>
    main()
  File "/home/agrosavia/cacao-hf/main.py", line 698, in main
    combined_metrics.add_batch(
  File "/home/agrosavia/cacao-hf/env/lib/python3.12/site-packages/evaluate/module.py", line 942, in add_batch
    evaluation_module.add_batch(**batch)
  File "/home/agrosavia/cacao-hf/env/lib/python3.12/site-packages/evaluate/module.py", line 546, in add_batch
    raise ValueError(error_msg) from None
ValueError: Predictions and/or references don't match the expected format.
Expected format: {'predictions': Sequence(feature=Value(dtype='int32', id=None), length=-1, id=None), 'references': Sequence(feature=Value(dtype='int32', id=None), length=-1, id=None)},
Input predictions: tensor([0, 0, 5, 3, 0, 0, 0, 1], device='cuda:0'),
Input references: tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
